### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by yilikunNEO** [chrunlee/163music-cli#1]
大佬,一直显示`env: node\r: No such file or directory`,貌似是`http://music.byyui.com`的api服务挂了?

**Comment by chrunlee** [comment]
没有啊，刚测试了下还是可以的... api 一直没怎么动过，你再试试呢? 如果还是出问题，再贴下详细信息看看呢
![image](https://user-images.githubusercontent.com/9331585/55368960-08b9f180-5527-11e9-996e-ccae7b95eabb.png)

**Comment by yilikunNEO** [comment]
![image](https://user-images.githubusercontent.com/43943437/55385828-97973000-5560-11e9-860b-12950bcbab8f.png)
这个需要先设置dir吗?  但是我用了`down -d ./music`也不行

![image](https://user-images.githubusercontent.com/43943437/55385901-c90ffb80-5560-11e9-85d2-694f6a6bf3e2.png)
我用的是Mac,是不是环境问题导致的呢?

**Comment by chrunlee** [comment]
额 mac 还真没用过..不好意思，我在windows 上的需要在某个目录下执行。mac上的话估计也是，需要在某个目录下执行，因为下载的文件会自动下载到对应目录，如果不在目录下执行也可以通过以下的方式：
`download -i 2730333440 -d d:/readmusic/`
通过 `-d` 来指定下载目录。
![image](https://user-images.githubusercontent.com/9331585/55386309-cc57b700-5561-11e9-8824-648791947238.png)
目录一定要存在，里面没做太大的兼容（自动创建文件夹之类的没有）

刚仔细看了下，应该是download 命令找不到，这个需要全局安装的。
`npm install music-163-load -g` 
带上`-g` . 

如果全局安装后还是不行的话，那可能是环境变量配置的问题，可以先试试 `node -v` `npm -v` 是否能够使用，不行的话就得需要配置环境变量了（mac没配置过呢，可以找找安装node的教程）。

**Comment by yilikunNEO** [comment]
是的,谢谢大佬,应该就是node的问题. 应该是node安装的目录不再env下,可能跟windows下的环境变量不太一致.另外强烈推荐大佬用mac开发啊,效率杠杠的,还没有太多linux兼容问题..

**Comment by chrunlee** [comment]
哈哈 一直想的，不过舍不得入手啊  . 
那我关闭了哈。
